import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {after} from 'node:test';
const base=process.env.FLOWPLAN_TEST_URL || 'http://localhost:5173';
assert.ok(['localhost','127.0.0.1'].includes(new URL(base).hostname));
async function req(path,method='GET',body){const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};}
const id=randomUUID(),path=`/api/workspaces/${id}`;
after(async()=>{const result=await fetch(base+path,{method:'DELETE'});assert.equal(result.status,204);});
assert.equal((await req('/api/workspaces','POST',{requestId:id,name:'RSVP verification',venue:'Local test hall',template:'sample'})).status,201);
let r=(await req(path)).data;
r.event.visitors=100;r.event.startTime='08:00';r.event.endTime='09:00';
r.event.items=r.event.items.map(i=>({...i,company:'',category:'',processingRate:120}));
assert.equal((await req(path,'PUT',{event:r.event,revision:r.revision})).status,200);
r=(await req(path)).data;
for(const name of ['RSVP Alpha','RSVP Beta']){const add=await req(path+'/companies','POST',{name,category:'Technology',revision:r.revision});assert.equal(add.status,200,JSON.stringify(add));r=add.data;}
assert.equal(r.event.rsvp.orderMode,'random');
assert.deepEqual(new Set(r.event.rsvp.order),new Set(r.event.companies.map(c=>c.id)));
assert.deepEqual((await req(path)).data.event.rsvp.order,r.event.rsvp.order);
const setupOrder=await req(path+'/rsvp','PATCH',{action:'order',revision:r.revision,order:r.event.companies.map(c=>c.id),skipped:[]});
assert.equal(setupOrder.status,200);r=setupOrder.data;
const profile={popularity:3,peakRate:2,dwell:30,staff:2,equipmentArea:1,storageArea:0,serviceRate:20,minimumArea:0,preferredLocation:'any',preferredNeighbors:[],avoidNeighbors:[],source:'estimated'};
for(const c of r.event.companies){const p=await req(path+'/rsvp','PATCH',{action:'profile',revision:r.revision,companyId:c.id,profile});assert.equal(p.status,200,JSON.stringify(p));r=p.data;}
const [a,b]=r.event.companies;
const metrics={visitors:10,intended:20,missedRate:.5,queueSeconds:60,exposure:30,density:1,coverage:.5,balance:.5,neighborVisitChange:0,companyScore:50,venueScore:50,score:50};
const request={companyId:a.id,seatId:'b1',size:{name:'Medium',w:5,h:3},revision:r.revision,requestId:randomUUID(),scenarios:[{seatId:'b1',label:'B01',metrics}],undersizedAcknowledged:true};
assert.equal((await req(path+'/rsvp','POST',{...request,companyId:b.id})).status,409);
assert.equal((await req(path+'/rsvp','POST',{...request,revision:r.revision-1})).status,409);
const results=await Promise.all([req(path+'/rsvp','POST',request),req(path+'/rsvp','POST',{...request,requestId:randomUUID()})]);
assert.equal(results.filter(r=>r.status===200).length,1,JSON.stringify(results));
r=results.find(r=>r.status===200).data;
assert.equal((await req(path+'/rsvp','POST',request)).status,200);
assert.equal(r.event.rsvp.records.length,1);
assert.equal((await req(path+'/claims','POST',{boothId:'b2',company:b.name,category:b.category,popularity:2,revision:r.revision})).status,409);
const renamed=await req(path+'/companies','PATCH',{oldName:a.name,name:'RSVP Alpha renamed',revision:r.revision});assert.equal(renamed.status,200);r=renamed.data;
assert.equal(r.event.companies.find(c=>c.name==='RSVP Alpha renamed').id,a.id);
const preserved=await req(path,'PUT',{event:{...r.event,name:'RSVP verification — persistence'},revision:r.revision});assert.equal(preserved.status,200,JSON.stringify(preserved));r=(await req(path)).data;
assert.equal(r.event.rsvp.records.length,1);assert.equal(r.event.companies[0].profile.popularity,3);
const release=await req(path+'/claims','DELETE',{boothId:'b1',company:'RSVP Alpha renamed',revision:r.revision});assert.equal(release.status,200);r=release.data;
assert.equal(r.event.rsvp.records[0].released,true);
const requeue=await req(path+'/rsvp','PATCH',{action:'requeue',revision:r.revision,companyId:a.id});assert.equal(requeue.status,200);r=requeue.data;
assert.deepEqual(r.event.rsvp.order,[b.id,a.id]);
const sizes=[{name:'Small',w:3,h:2},{name:'Medium',w:5,h:3},{name:'Large',w:7,h:4}];
const advanced=await req(path+'/rsvp','PATCH',{action:'settings',revision:r.revision,sizes,
  seats:[{id:'b2',policy:{price:75,requiredCategory:'Technology'}}],protectedAreas:[{x:0,y:0,w:1,h:1}]});
assert.equal(advanced.status,200);r=advanced.data;
const beforeRevision=r.revision;
const simple=await req(path+'/rsvp','PATCH',{action:'simple-settings',revision:r.revision,orderMode:'alphabetical',sizes,seatId:'b2',price:0});
assert.equal(simple.status,200);r=simple.data;
assert.equal(r.revision,beforeRevision+1);
assert.deepEqual(r.event.rsvp.order,[a.id,b.id]);
assert.equal(r.event.rsvp.records.length,1);
assert.equal(r.event.rsvp.protectedAreas.length,1);
assert.deepEqual(r.event.items.find(i=>i.id==='b2').reservationPolicy,{price:0,requiredCategory:'Technology'});
assert.equal((await req(path+'/rsvp','PATCH',{action:'simple-settings',revision:beforeRevision,orderMode:'manual',sizes,seatId:'b2',price:100})).status,409);
const unchanged=await req(path+'/rsvp','PATCH',{action:'simple-settings',revision:r.revision,orderMode:'registration',sizes,seatId:'__available'});
assert.equal(unchanged.status,200);r=unchanged.data;
assert.equal(r.event.items.find(i=>i.id==='b2').reservationPolicy.price,0);
const randomDraw=await req(path+'/rsvp','PATCH',{action:'simple-settings',revision:r.revision,orderMode:'random',sizes,seatId:'__available'});
assert.equal(randomDraw.status,200);r=randomDraw.data;
const drawnOrder=r.event.rsvp.order;
assert.equal(r.event.rsvp.orderMode,'random');
const savedAgain=await req(path+'/rsvp','PATCH',{action:'simple-settings',revision:r.revision,orderMode:'random',sizes,seatId:'__available'});
assert.equal(savedAgain.status,200);r=savedAgain.data;
assert.deepEqual(r.event.rsvp.order,drawnOrder);
console.log('Sequential reservation integration checks passed.');
